### PR TITLE
Implementation of reader constructor

### PR DESCRIPTION
**Pull request by bxshi**
I Implement the constructor of `rdf::reader` so it can be constructed with `file_path` now.

### CODE REVIEW

**Comment by bxshi** [comment]
Hi @bendiken, would you mind verifying this PR? Thanks!

**Comment by artob** [comment]
Thanks for the submission, will get to this tomorrow.

**Comment by artob** [comment]
Thanks for your contribution! I've now merged it, and have added you to the `CREDITS` file.

From my review, this does still need a bit of further work for how the exception strings are constructed. Right now, the string concatenation means that a number of temporaries are allocated on the heap, which could in and of itself throw an `std::bad_alloc`. So, that will need to be changed to using `std::snprintf()` on a stack-allocated temporary buffer. But I can take care of that later.

**Comment by bxshi** [comment]
Thanks for pointing this out. I am not aware of such issue.
I have modified the code and will submit another PR.

**Pull request merged**
